federation_version: 2 # Without this line, Rover uses Federation 1
subgraphs:
  merchants:
    routing_url: http://localhost:4001/
    schema:
      subgraph_url: http://localhost:4001/
  transactions:
    routing_url: http://localhost:4002/
    schema:
      subgraph_url: http://localhost:4002/